export const FLOORS = [0, 3.6, 7.2];
export const KEY_NAMES = { bronze: "Brass", silver: "Silver", gold: "Gold" };
export const ROOMS = [
  {
    id: "antechamber",
    name: "The Antechamber",
    subtitle: "A rather peculiar welcome",
    tint: 0x798477,
    entry: { x: -9, floor: 0 },
    objective: "A key to the unknown",
    description:
      "Find the brass key and work your way up to the door on the highest walkway.",
    hint: "Collect the brass key with E. The red switch lowers the blue field for 8 seconds. Climb the right ladder, then the left ladder.",
    ladders: [
      { x: 7, from: 0, to: 1 },
      { x: -5, from: 1, to: 2 },
    ],
    poles: [],
    keys: [{ id: "bronze", x: -6.5, floor: 0 }],
    switches: [
      {
        id: "field",
        kind: "field",
        x: -2.5,
        floor: 0,
        label: "Lower force field",
      },
    ],
    fields: [{ x: 2, floor: 0, switch: "field" }],
    lightning: [],
    traps: [],
    conveyors: [],
    enemies: [],
    teleporters: [],
    doors: [
      {
        x: 9,
        floor: 2,
        target: 1,
        key: "bronze",
        label: "Enter the Sunken Crypt",
      },
    ],
  },
  {
    id: "crypt",
    name: "The Sunken Crypt",
    subtitle: "Let sleeping things lie",
    tint: 0x647c78,
    entry: { x: -9, floor: 0 },
    objective: "Disturb the silence",
    description:
      "Something stirs on the middle walkway. Reach the upper door without joining the residents.",
    hint: "Climb the first ladder, turn left, and open the trapdoor with the switch. The mummy will fall if it follows. The next ladder is on the far left.",
    ladders: [
      { x: -3, from: 0, to: 1 },
      { x: -7, from: 1, to: 2 },
    ],
    poles: [{ x: 8, from: 2, to: 0 }],
    keys: [],
    switches: [
      { id: "trap", kind: "trap", x: -5, floor: 1, label: "Toggle trapdoor" },
    ],
    fields: [],
    lightning: [],
    traps: [{ x: 3, width: 2.4, floor: 1, switch: "trap" }],
    conveyors: [],
    enemies: [
      {
        id: "mummy",
        kind: "mummy",
        x: 6.8,
        floor: 1,
        min: -9,
        max: 9,
        speed: 1.05,
      },
    ],
    teleporters: [],
    doors: [
      {
        x: -9,
        floor: 0,
        target: 0,
        arrival: { x: 8, floor: 2 },
        label: "Return to the Antechamber",
      },
      { x: 9, floor: 2, target: 2, label: "Ring the laboratory bell" },
    ],
  },
  {
    id: "laboratory",
    name: "The Laboratory",
    subtitle: "An electrifying discovery",
    tint: 0x677f83,
    entry: { x: -9, floor: 0 },
    objective: "A silver lining",
    description:
      "Silence the lightning machine, recover the silver key, and test the doctor’s matter transmitter.",
    hint: "The yellow lever on the middle floor switches off the lightning. Take the silver key on the right. Upstairs, use the blue transmitter to bypass the second machine.",
    ladders: [
      { x: -6, from: 0, to: 1 },
      { x: 8, from: 1, to: 2 },
    ],
    poles: [],
    keys: [{ id: "silver", x: 6, floor: 1 }],
    switches: [
      {
        id: "power",
        kind: "power",
        x: -3.4,
        floor: 1,
        label: "Toggle lightning machine",
      },
    ],
    fields: [],
    lightning: [
      { x: 1, floor: 1, switch: "power" },
      { x: 3, floor: 2 },
    ],
    traps: [],
    conveyors: [],
    enemies: [],
    teleporters: [
      { x: 6, floor: 2, toX: -7, toFloor: 2 },
      { x: -7, floor: 2, toX: 6, toFloor: 2 },
    ],
    doors: [
      {
        x: -9,
        floor: 0,
        target: 1,
        arrival: { x: 8, floor: 2 },
        label: "Return to the Crypt",
      },
      {
        x: -9.2,
        floor: 2,
        target: 3,
        key: "silver",
        arrival: { x: -8, floor: 2 },
        label: "Enter the Moonlit Gallery",
      },
    ],
  },
  {
    id: "gallery",
    name: "The Moonlit Gallery",
    subtitle: "The only way is down",
    tint: 0x71738b,
    entry: { x: -8, floor: 2 },
    objective: "A change in perspective",
    description:
      "Descend through the gallery and find the passage to the heart of the castle.",
    hint: "Walk to the brass pole in the center and hold down to slide to the ground floor. Use the red switch on the left, then cross the field to the right-hand door.",
    ladders: [
      { x: -7, from: 0, to: 1 },
      { x: 7, from: 1, to: 2 },
    ],
    poles: [{ x: 0, from: 2, to: 0 }],
    keys: [],
    switches: [
      {
        id: "field",
        kind: "field",
        x: -3,
        floor: 0,
        label: "Lower force field",
      },
    ],
    fields: [{ x: 4, floor: 0, switch: "field" }],
    lightning: [],
    traps: [],
    conveyors: [{ min: -6, max: 5, floor: 1, speed: 1.4 }],
    enemies: [],
    teleporters: [],
    doors: [
      {
        x: -9.2,
        floor: 2,
        target: 2,
        arrival: { x: -8, floor: 2 },
        label: "Return to the Laboratory",
      },
      { x: 9, floor: 0, target: 4, label: "Ring the engine room bell" },
    ],
  },
  {
    id: "engine",
    name: "The Engine Room",
    subtitle: "The heart of the beast",
    tint: 0x8b7864,
    entry: { x: -9, floor: 0 },
    objective: "All that glitters",
    description:
      "Turn the doctor’s machines against his creation and claim the last key.",
    hint: "The yellow lever turns off the middle-floor lightning. Climb on the right. At the top, use the trapdoor switch by the ladder to stop the monster before taking the gold key.",
    ladders: [
      { x: -6, from: 0, to: 1 },
      { x: 6, from: 1, to: 2 },
    ],
    poles: [{ x: 9.7, from: 2, to: 0 }],
    keys: [{ id: "gold", x: 8.1, floor: 2 }],
    switches: [
      {
        id: "power",
        kind: "power",
        x: -4,
        floor: 1,
        label: "Toggle lightning machine",
      },
      { id: "trap", kind: "trap", x: 5.5, floor: 2, label: "Toggle trapdoor" },
    ],
    fields: [],
    lightning: [{ x: 1, floor: 1, switch: "power" }],
    traps: [{ x: 1.5, width: 2.5, floor: 2, switch: "trap" }],
    conveyors: [{ min: -3, max: 4.5, floor: 1, speed: -1.25 }],
    enemies: [
      {
        id: "creature",
        kind: "creature",
        x: -5,
        floor: 2,
        min: -9,
        max: 9,
        speed: 1.3,
      },
    ],
    teleporters: [],
    doors: [
      {
        x: -9,
        floor: 0,
        target: 3,
        arrival: { x: 8, floor: 0 },
        label: "Return to the Gallery",
      },
      {
        x: 9.2,
        floor: 2,
        target: 5,
        key: "gold",
        label: "Enter the Last Watch",
      },
    ],
  },
  {
    id: "gatehouse",
    name: "The Last Watch",
    subtitle: "One last courtesy",
    tint: 0x868067,
    entry: { x: -9, floor: 0 },
    objective: "Leave no key unturned",
    description:
      "The exit is in sight. Climb to the final gate and turn all three keys. Freedom is so close.",
    hint: "Climb the left ladder. Press the red switch and cross the middle-floor field before it returns. Climb the right ladder and use all three keys at the large central gate.",
    ladders: [
      { x: -6, from: 0, to: 1 },
      { x: 7, from: 1, to: 2 },
    ],
    poles: [],
    keys: [],
    switches: [
      {
        id: "field",
        kind: "field",
        x: -3.5,
        floor: 1,
        label: "Lower force field",
      },
    ],
    fields: [{ x: 1.5, floor: 1, switch: "field" }],
    lightning: [],
    traps: [],
    conveyors: [],
    enemies: [],
    teleporters: [],
    doors: [
      {
        x: -9,
        floor: 0,
        target: 4,
        arrival: { x: 8, floor: 2 },
        label: "Return to the Engine Room",
      },
      {
        x: 0,
        floor: 2,
        target: "win",
        key: "all",
        label: "Unlock the final gate",
      },
    ],
  },
];
